[package]
name = "mcmc-decrypt"
version = "0.1.0"
authors = ["Tom Milligan <tommilligan@users.noreply.github.com>"]

[dependencies]
clap = "2.32"
rand = "0.6"
rand_core = "0.3"
rand_pcg = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
